### ISSUE TITLE
[Bug Report]: Enbrighton- ZW4006 - 26931 - V5.39

### ISSUE THREAD

**Issue by jr-air** [jascoproducts/firmware#110]
### What brand is the bug report for?

Enbrighten-GE

### ZW Number

ZW4006

### Product Number

26931

### FW Version

v5.39

### Bug Report Details

No Security support in firmware. Please include at least S0 if possible

### How To Reproduce

Tried inclusion/exclusion and re-interview multiple times

**Comment by jascoproducts** [comment]
@jr-air Thank you for your request. Unfortunately due to Z-Wave Alliance guidelines for many years now, no product can be certified without S2 Security. This product was designed and brought to market before this requirement went into effect and as a result it does not contain enough memory to accommodate either S0 or S2.
