### ISSUE TITLE
[Firmware Request]: GE Enbrighten ZW4002 - 55258 5.51 stable firmware (beta has been available for over 2 years)

### ISSUE THREAD

**Issue by happyshow** [jascoproducts/firmware#123]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW4002

### Product Number

55258

**Comment by jascoproducts** [comment]
@happyshow The beta releases of firmware are released as a way to offer additional support for legacy products. Due to the age of the product and chipset version (500 series), we no longer able to certify future releases with the Z-Wave Alliance. We still run through all available testing plans and the Z-Wave Alliance Certification Test Tool but we cannot release an officially certified version of the firmware.
