### ISSUE TITLE
[Firmware Request]: UltraPro - ZWA3016 - 59350-2

### ISSUE THREAD

**Issue by glenne** [jascoproducts/firmware#124]
### What brand is the request for?

UltraPro

### ZW Number

ZWA3016

### Product Number

59350-2

**Comment by glenne** [comment]
I currently have version 1.23.  I tried the ZWA3016_UltraPro_59350_1.25.gbl file using Hubitat but it said the 'The transferred image does not match the Firmware Target'

**Comment by jascoproducts** [comment]
Thanks. We're looking into this.

**Comment by jascoproducts** [comment]
@glenne Just replaced the existed v1.25 with a newly coded version specific to 59350. Let us know if this solves your issue.

**Comment by heatvent** [comment]
Hi, I was looking to update my GE Enbrighten ZWA3016 dimmers with the firmware from here:

https://github.com/jascoproducts/firmware/tree/main/zwave/Enbrighten-GE/ZWA3016/58438%20-%20In-Wall%20Paddle%20Dimmer%2C%20700S/1.25

There is reference to this issue (#124). However, this seems to be an UltraPro firmware rather than a GE Enbrighten firmware. When I try to update with Hubitat to a GE ZWA3016 it says it does not match the target.
