### ISSUE TITLE
[Firmware Request]: UltraPro - ZW3010 - 39351/54897/54898

### ISSUE THREAD

**Issue by crxporter** [jascoproducts/firmware#8]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW3010

### Product Number

13113

**Comment by jascoproducts** [comment]
@crxporter Similar to the ZW4002, the product number you have provided is likely the PIN number under the QR code. I can identify it if you can tell me what Logo is in the top left specifically, and if you have a QR code sticker in the bottom right.

**Comment by crxporter** [comment]
You're likely correct I'm looking at the "Product ID" in decimal form from my instance of zwave-js. UltraPro is almost definitely what this device is.

Is there a way to properly convert this format of "Product ID" over to the number you're looking for - so that I (we) can properly find which of my devices go with which firmware files?

![image](https://user-images.githubusercontent.com/38265886/173640846-46c21bdd-e07a-4778-bdcd-a07ecefd8b2c.png)

**Comment by jascoproducts** [comment]
@crxporter We are working through all the documentation currently to try to be as comprehensive as possible for whatever number, hex value, etc. that you might come across.
We cant completely rely on zwave-js and other databases because we do not know what data they have input as definitions for what our products report. This being an example since it was input as GE/Jasco when the product is actually UltraPro. 
We are working to scrub any wrong data we find, but are not there just yet. 
Right now, the best way to identify the product is physically, using the Identifying Your Product section of the readme. We are updating the Firmware Request form to better provide information in the meantime.
