### ISSUE TITLE
[Bug Report]: BRAND - ZW NUMBER - PRODUCT NUMBER - FW VERSION

### ISSUE THREAD

**Issue by awgneo** [jascoproducts/firmware#87]
### What brand is the bug report for?

Enbrighten-GE

### ZW Number

ZW3008

### Product Number

26933-2

### FW Version

5.32

### Bug Report Details

Even at low motion detection mode (parameter 13) and with switch mode enabled (parameter 16) there is still a 2-3 second delay with significant motion right in front of the sensor. This is the case with all nine of my motion dimmers.

### How To Reproduce

See bug report.

**Comment by jascoproducts** [comment]
We appreciate the information you provided for this and apologize for the delay in responding, however we were trying to duplicate the results and other products were in front of this getting completed. 

Parameter 13 is Motion Sensitivity. Turning it to low sensitivity, is decreasing the sensitivity and will require more motion in order to trigger the sensor. you would want the sensitivity to be set to the highest (1) level if you are concerned about detection in the room. We tested all sensitivities and with switch mode enabled and disabled and could not duplicate a "delay". As soon as the sensor detects motion, it instantly sends a motion alert, and turns the light on. If switch mode is enabled, the light will instantly turn on with no ramping up. If switch mode is disabled, the light will gradually ramp from 0 to the desired setting.
